import Head from "next/head";
import Link from "next/link";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="d-flex vh-100 justify-content-center align-items-center">
        <Link href="/checkout/prod_001"
          className="btn btn-primary"
        >
          Aller à la page de paiement du produit 1
        </Link>
      </main>
    </>
  );
}
